### ISSUE TITLE
Bridge error

### ISSUE THREAD

**Issue by nils-kt** [khanhas/Spicetify#105]
Hello, I wanted to try a few functions, but I always get an error. Does this have anything to do with the internal Spotify API? (Rate-Limit)

`Error:  (bridge message: 'track_metadata', args: ["spotify:track:6ebkx7Q5tTxrCxKq4GYj0Y"])
    at zlink.bundle.js:16
    at zlink.bundle.js:16`

```js
Spicetify.BridgeAPI.request("track_metadata", ["spotify:track:6ebkx7Q5tTxrCxKq4GYj0Y"], (e, p) => {
	console.log(p);
	console.log(e);
});
```

When I hand over like this `["spotify:track:6ebkx7Q5tTxrCxKq4GYj0Y"]`, it works. If I hand it over a Websocket it doesn't work. Does anyone have any idea why?

**Comment by khanhas** [comment]
1. I don't think there is a limit on anything.
2. Your code block works perfectly on mine.
3. What do you hand over a Websocket? I don't quite understand.

Anyway, I'm no longer maintaining this repo because I can't spend time on both "Spicetify" for Rainmeter and "spicetify-cli". "spicetify-cli" supports more platforms and it's easier for me to add new features.
You can try it if you want:
1. In Spicetify for Rainmeter skin, hit Restore and Delete Backup
2. Open Powershell and run: 
```powershell
iwr https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1 | iex
```
3. In Powershell, follow these step: https://github.com/khanhas/spicetify-cli#basic-usage

**Comment by nils-kt** [comment]
I have created a screenshot for you:
![Image](https://i.imgur.com/k0Hao36.png)

I have the same problem with "spicetify-cli".

**Comment by khanhas** [comment]
Can I have the code that routes WebSocket messages (`websocket.onmessage`)?

**Comment by khanhas** [comment]
If you can, just give me all of the code you working on :)

**Comment by Bluscream** [comment]
> Anyway, I'm no longer maintaining this repo because I can't spend time on both "Spicetify" for Rainmeter and "spicetify-cli". "spicetify-cli" supports more platforms and it's easier for me to add new features.

Can't you just instead of ditching this repo alltogether use spicetify **only** as a UI wrapper? So that spicetify downloads and installs the cli on first start and executes command line stuff based on what the user clicks. So it's way less maintainence work :o

**Comment by nils-kt** [comment]
> If you can, just give me all of the code you working on :)

I sent you the code at Discord. :)
