### ISSUE TITLE
Problem with JsonBin

### ISSUE THREAD

**Issue by TheLongLife** [khanhas/Spicetify#19]
It's me again...I've run into another problem.
I've created a blank json on JsonBin and I've put the access URL in the `Trashbin.js` but it doesn't seem to work...when I restart the Spotify all the songs that I've put into the trash are playable again.

Something suspicious that I've noticed is that in your example for access URL (//api.jsonbin.io/b/5aXXXXXXXXXXXXXXX23e4) ends with "23e4" but my URL does not...

I've tried creating private as well as public bin but it doesn't work either way.

**Comment by khanhas** [comment]
URL just should looks "like" that, it could be anything, end or start part of example URL is not a requirement.   
Your JsonBin should be public.
After you added url to constant `jsonBinURL`, did you Re-apply?
Also, trash list stored in local storage won't be migrate to jsonBin since I think it could cause conflict. You have to gather trash list again.

**Comment by TheLongLife** [comment]
Welp 3rd time lucky I guess.  I tried it once more and it works.

I did re-apply and restart spotify every time I changed the constant and I did realize that the local storage wouldn't be transferred so I trashed a new song and after the restart the song was not in the trash anymore.

It works now though. Who knows where I messed up.
Sorry for bothering you xD
