### ISSUE TITLE
Issues with font

### ISSUE THREAD

**Issue by ghost** [khanhas/Spicetify#2]
As far as I can see, there's no way to change the font color in the interface. [This](https://puu.sh/zh1YE/3fffe4cbde.png) is what my spotify looks like as a result. What do I do? 

Also, I think it could be helpful if you could upload a zip folder of the .spa files you use in your config in the screenshot.

Thanks.

**Comment by khanhas** [comment]
Color of text is usually called "FG", try to change those.
If they aren't any different, you need to Restore -> Clear backup -> Backup again. Then Apply.  
It's unnecessary to include my spa file since if you follow the instruction correctly and don't change anything in color scheme and CSS, your client will be exactly like mine.

**Comment by ghost** [comment]
Close this issue.

I am an idiot.
