### ISSUE TITLE
[Request] User info back at top right

### ISSUE THREAD

**Issue by Sparoney** [khanhas/Spicetify#23]
![image](https://user-images.githubusercontent.com/38852913/39663153-30ed83fe-50b1-11e8-921e-b08e5046bd76.png)

Just a request if its possible to restore the username/Facebook name and profile picture of your account back in the top bar next to the menu arrow.

Thanks!

**Comment by khanhas** [comment]
It's in User.css, find `.profile.content-top-bar__profile-link`

**Comment by Sparoney** [comment]
Thank you! I should stop making these issues and check the CSS myself haha

**Comment by Sparoney** [comment]
Update:
I removed `.profile.content-top-bar__profile-link` from

> /*Hide some annoying elements like profile name and pic, upgrade button and device connect bar at bottom, new playlist button*/
> .upgrade-button,
> .view-player .remote-playback-bar,
> .NewPlaylistButton {
> 	display: none !important;
> }

in the code and it is still missing. There are no other times when this part of the CSS is used.

I've updated the CSS, re-applied, and restarted, something else must be modifying it?

When maximising the Spotify window, I can see my name appear for a split second.

**Comment by khanhas** [comment]
Because its position somewhat relative to right sidebar (`buddy-list`).
When right sidebar is minimize (not hovering on), profile pic and name are all the way to the right. And window control box covers them. So I suggest you also retrieve right sidebar to its original state:
Comment out those parts like this:

![image](https://user-images.githubusercontent.com/26436809/39663672-c3b920b8-50a1-11e8-9ebb-e36a09db433b.png)

![image](https://user-images.githubusercontent.com/26436809/39663694-2c98962c-50a2-11e8-8686-6a8dd2678a40.png)

![image](https://user-images.githubusercontent.com/26436809/39663676-d2cafc16-50a1-11e8-8558-e6b4d84a8e0f.png)
