### ISSUE TITLE
Friend Feed has no style attached

### ISSUE THREAD

**Issue by mangogelato** [khanhas/Spicetify#39]
Upgraded to Spicetify 1.6.6 and it's working almost completely flawlessly, although I have one problem: the friend feed has no style, like this:
![image](https://user-images.githubusercontent.com/38873298/41138841-67f59158-6b27-11e8-9675-fb2779c80327.png)
The left bar is working fine, but not the right bar
If it helps, I'm on Windows 10 and my Documents folder is in a OneDrive folder

**Comment by khanhas** [comment]
Can you access `%appdata%\Spotify\Apps\buddy-list\css` and check if `styles.css` is in there?

**Comment by mangogelato** [comment]
There is a file called style not styles

On 8 Jun 2018, at 3:08 pm, khanhas <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you access %appdata%\Spotify\Apps\buddy-list\css and check if styles.css is in there?

**Comment by khanhas** [comment]
Oops. yeah `style`.  
Open `index.html` in buddy-list folder, does it look like this:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://zlink.app.spotify.com/css/glue.css">
  <link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" class="spicetify-userCSS" href="https://zlink.app.spotify.com/css/user.css"></head>
<body>
  <div id="root" data-play-source="buddy-list"></div>
  <!-- "init.js" is served by the desktop client and provides the "window.__spotify" object. -->
  <script src="init.js"></script>
  <script src="bundle.js"></script>
</body>
</html>
```

**Comment by khanhas** [comment]
I just tried. It will look like that If html file doesn't have `glue.css` stylesheet.

**Comment by mangogelato** [comment]
How do I go about getting the glue.css stylesheet?

________________________________

**Comment by khanhas** [comment]
So does you index.html has `glue.css` declaration as mine? If it does, it should works normally.  
Since the whole client depends on one same glue.css. And you said the rest of UI works fine, then no reason it doesn't apply that stylesheet.  
Have you tried restore then apply again?

If it still doesn't work, manually follow these steps:
1. Open index.html
Replace `https://zlink.app.spotify.com/css/glue.css` with `css/glue.css`
2. Copy glue.css from `%appdata%\Spotify\zlink\css` to `%appdata%\Spotify\Apps\buddy-list\css`
3. Restart/Reload the client and it should works normally.
Any Re-apply/Apply action will revert back what you do, so be careful.

**Comment by mangogelato** [comment]
I reinstalled Spotify and Spicetify and it seems to be working fine as of now.

________________________________
