### ISSUE TITLE
Small now playing's album picture appeared

### ISSUE THREAD

**Issue by angeloanan** [khanhas/Spicetify#5]
When clicking the up arrow button on the now playing album picture in the bottom, a small picture of the current playing album appears. The small picture becomes bigger when the sidebar is opened.

Picture:
https://angelo.took-naughty.pictures/KBSIDzHGs.png

GIF of opening the sidebar
https://angelo.took-naughty.pictures/keRZDRVgT.gif

**Comment by khanhas** [comment]
This "small artwork big artwork" interaction needs more investigation in original CSS file. 
Maybe their behavior are controlled by Javascript. Honestly, I don't know and I don't have motivation to get there since this is my personal theme and it's enough for me.  
I released this theme with pure purpose is to demonstrate how you can customize and modify on your own. Pick it where I left so you guys don't need to go through the whole finding and searching process as I did.

**Comment by angeloanan** [comment]
Would you mind if I try to investigate/fix it? No guarantees though.

_Sent from my Redmi 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
