### ISSUE TITLE
Spicetify Errors

### ISSUE THREAD

**Issue by AbyssalSquid** [khanhas/Spicetify#90]
As of today, JAnuary 1st 2019, spicetify is causing the following error in rainmeter:

"Web Side Error:Error updating rating for Spotify Desktop"

**Comment by AbyssalSquid** [comment]
After double checking, restoring Spotify to its defaults causes the error to stop.

**Comment by khanhas** [comment]
Not happening in mine. What is your skin?

**Comment by AbyssalSquid** [comment]
I'm using version 1.7.7 of Spicetify with version 2.0.2 of Monstercat-Visualizer. I've tried uninstalling both skins and doing a complete reinstall of Spotify. The error also occurs with other vizualizer skins. The error goes away if I unload all of the skins from a vizualizer.

**Comment by khanhas** [comment]
Can you open Console and paste this in:
```javascript
(function() {
    const heart = document.querySelector('[data-interaction-target="heart-button"]');

    const isHeartAvailable = heart.style.display !== "none";
    if (isHeartAvailable) {
        if (heart.classList.contains("active")) {
            return 5;
        }

        return 0;
    } else {
        const add = document.querySelector('[data-button="add"]');
        if (add.attributes["data-interaction-intent"].value === "remove") {
            return 5;
        }

        return 0;
    }
})()
```
see if it throws any error or returns correctly (5 for Liked track, 0 Not-liked track)

**Comment by AbyssalSquid** [comment]
VM233:13 Uncaught TypeError: Cannot read property 'value' of undefined
    at <anonymous>:13:55
    at <anonymous>:19:3

**Comment by khanhas** [comment]
What is your Spotify version? If it's the newest one (1.0.96), it should work exactly like mine and others.  
Anyway, I can't find any problem with that block of code but I have another solution to get Rating state:
1. Open `%userprofile%\Documents\Rainmeter\Skins\Spicetify\Extensions\wnpPlugin.js` file
2. Go to line 349, you can see whole block of `musicInfo.rating` function, replace it with this:
```javascript
musicInfo.rating = () => Spicetify.LiveAPI(Spicetify.Player.data.track.uri).get("added") ? 5 : 0;
```

Code should look like this after replacement:
![image](https://user-images.githubusercontent.com/26436809/50757174-139b1800-1291-11e9-8a15-eab0ecd4b214.png)

3. Save wnpPlugin.js file and hit Re-apply in Spicetify

Since I am developing `spicetify-cli`, which has same feature set as Spicetify, I stop updating this repo and will archive it soon when I finish porting everything over.

**Comment by AbyssalSquid** [comment]
Thanks, that seems to have resolved the error. The only issue I'm having now is that the visualizer itself isn't working, almost like webnowplaying isn't detecting sound volume from spotify.

**Comment by khanhas** [comment]
AudioPlugin problem doesn't relate here. I think you should find answer in Rainmeter forum.
